### ISSUE TITLE
Feature Request: Quickly resize window when dragged to corners

### ISSUE THREAD

**Issue by mansoormemon** [Nintersoft/CustomTitlebar#1]
Can you add the tiling feature which automatically resizes window when dragged to corners.

The shortcuts are working thou.

**Comment by mauromascarenhas** [comment]
I'll certainly have a look at this feature (I have even forgot about it when developing this project).
Thank you for the reminder.

It will be probably available on future releases :)

**Comment by mauromascarenhas** [comment]
Support to native system move/resize (brought by Qt 5.15) has been implemented for static version (see e80a46e). Thus, this issue must be closed with the v3.x release of QCustomWindow.
